server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment-get  #路由的id , 没有固定的规则 , 但是要求唯一 , 建议配合服务名称
          uri: localhost:8001   #服务的host路径
          predicates:    # 断言 , 将路径相匹配的进行路由
             - Path=/payment/get/**
        - id: payment-getLb  #路由的id , 没有固定的规则 , 但是要求唯一 , 建议配合服务名称
          uri: localhost:8001   #服务的host路径
          predicates:    # 断言 , 将路径相匹配的进行路由
             - Path=/payment/lb
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka





